### ISSUE TITLE
A problem I occur while read in the images

### ISSUE THREAD

**Issue by miaojiang1987** [hvy/chainer-inception-score#4]
Dear Yamazaki-san,

I have no issue with the example code. However, after I load my own images, the program will report such a issue:

(60000, 3, 32, 32)
Batch size: 100
Total number of images: 60000
Total number of batches: 600
Running batch 1 / 600 ...
Traceback (most recent call last):
  File "example.py", line 64, in <module>
    main(args)
  File "example.py", line 56, in main
    mean, std = inception_score(model, images_array)
  File "/home/hoosierai/Documents/github/chainer-inception-score/inception_score.py", line 47, in inception_score
    ims_batch = F.resize_images(ims_batch, (299, 299))  # bilinear
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/functions/array/resize_images.py", line 159, in resize_images
    return ResizeImages(output_shape).apply((x,))[0]
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/function_node.py", line 243, in apply
    self._check_data_type_forward(in_data)
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/function_node.py", line 328, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/functions/array/resize_images.py", line 21, in check_type_forward
    x_type.ndim == 4
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/utils/type_check.py", line 524, in expect
    expr.expect()
  File "/home/hoosierai/.local/lib/python3.6/site-packages/chainer/utils/type_check.py", line 482, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType: 
Invalid operation is performed in: ResizeImages (Forward)

Expect: in_types[0].dtype.char == f
Actual: B != f

I have carefully checked the dimension of my datasets, it is same with the example code's 60000*3*32*32, and type is also ndarray, do you know why I caused this error?

I really appreciate your reply!

Best,
Miao

**Comment by miaojiang1987** [comment]
Dear Yamazaki-san,

Sorry to trouble you, again.

If you cannot figure out what happens to this. Could you or someone else give instructions on how to load generated images ( not the example images)? I tried to reproduce with my own dataset but it will stuck at the point.

Best,
Miao

**Comment by hvy** [comment]
This output says that there is a type mismatch. 

```python
Expect: in_types[0].dtype.char == f
Actual: B != f
```

More specifically, your images are of dtype `B` unsigned byte, while the library expects an `f` i.e. a float. Could you try casting the images to float before passing them to the Inception score function?

**Comment by miaojiang1987** [comment]
Thanks Yamazaki-san! お疲れ様でした

**Comment by hvy** [comment]
I take it as you fixed it. Let me close this ticker for now.
